alias gitrekt='git push origin master'
alias gitbent='git pull origin master'
alias wtf='git status'
alias such='git'
alias very='git'
alias wow='git commit -a'
alias githist='git log --diff-filter=AD --summary'
alias addupstream='git remote add upstream'
alias addorigin='git remote add origin'
alias redshift='cd ~/usr/local/bin && redshift-gtk'
